# ingestion:
#   persist-dir: app/chatbot/tmp/vectorstore

retrieval:
  persist-dir: /mnt/10TB/iordanissapidis/SemanticRAG/retrieval_store
  score-threshold: 0.4
  topk: 5

generation:
  model: llama3.1:8b
  prompts:
    system: "Respond to all questions in a direct manner and explain your answer briefly. If provided with facts, pay very close attention to it"
    rag_prompt: >
      Review all provided data carefully.
      Start with your conclusion. Then list only the documents used, each with a brief explanation.
      Use multiple documents if needed, but avoid those that repeat the same info or are irrelevant.
      Only include documents essential to answering the question.
      If nothing is relevant, say so and answer from your own knowledge.
      You are given the following data:


tmp-dir: /mnt/10TB/iordanissapidis/SemanticRAG/tmp
doc-dir: /mnt/10TB/iordanissapidis/SemanticRAG/documents