# ingestion:
#   persist-dir: app/chatbot/tmp/vectorstore

retrieval:
  persist-dir: /mnt/10TB/iordanissapidis/vectorstores
  score-threshold: 0.6
  topk: 6

generation:
  model: llama3.1:8b
  prompts:
    system: "Respond to all questions in a direct manner and explain your answer briefly. If provided with fatcs, pay very close attention to it"
    rag_prompt: >
      Examine all the provided data carefully and answer according to the given data. 
      If the data is relevant but contain conflicting facts, you must mention that the data contain conflicts and state those conflicts
      If the data is completely irrelevant,you must mention that no relevant data are provided and answer according to your knowledge.
      You are given the following data:


