ingestion:
  persist-dir: app/chatbot/tmp/vectorstore
  # dataset-dir: datasets/MarineRestorationAnalysis/pdf

retrieval:
  persist-dir: /mnt/10TB/iordanissapidis/datasets/vectorstore
  score-threshold: 0.6

generation:
  model: llama3.1:8b