# ingestion:
#   persist-dir: app/chatbot/tmp/vectorstore

retrieval:
  persist-dir: /mnt/10TB/iordanissapidis/SemanticRAG/retrieval_store
  score-threshold: 0.0
  topk: 6

generation:
  model: llama3.1:8b
  temperature: 0.01
  prompts:
    system: "Respond to all questions in a direct manner and explain your answer briefly."
    rag_prompt: >
      Review all provided document snippets.
      Mention the number of every snippet you use, each with a brief explanation.
      The answer may be split across two or more snippets so use multiple snippets if needed.
      ONLY include documents essential to answering the question.
      If they do not, clearly state it.
      You are given the following data:

    kgrag_prompt: >
      Review all provided document snippets to answer.
      The answer may be split across two or more snippets so use multiple snippets if needed.
      Mention the number of every snippet you use, each with a brief explanation.
      ONLY mention snippets that are essential to answering the question.
      If they do not, clearly state it.
      There may be snippets that do not directly answer the question themselves 
      but can be combined with other snippets to provide a full answer.
      You are given the following data:


tmp-dir: /mnt/10TB/iordanissapidis/SemanticRAG/tmp
doc-dir: /mnt/10TB/iordanissapidis/SemanticRAG/documents